# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

matrix:
  include:
    - os: linux
      dist: trusty
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

    - os: linux
      dist: trusty
      r: release
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

  allow_failures:
    - os: linux
      dist: trusty
      r: devel


language: R
sudo: false
cache: packages

notifications:
  email:
    on_success: never
    on_failure: never
    
r_github_packages:
  - jimhester/covr
    
after_success:
    - Rscript -e 'covr::codecov()'
